# -*- coding: utf-8 -*-
"""🤖 AI Converstational Data Science Tutor🎓🚀.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClnODphJg93eok65Y74rtewkSj_qYSdE
"""

! pip install streamlit -q

pip install langchain-google-genai

!pip install langchain-google-genai

!pip install langchain-google-genai
# restart runtime (Runtime > Restart runtime) - This is a comment, not executable code

pip install langchain_experimental

import langchain_experimental
print(langchain_experimental.__version__)

import sys
print(sys.executable)

pip install --upgrade langchain langchain_experimental

from google.colab import drive
drive.mount('/content/drive')

import os

file_path = "AIzaSyDqMz_ResrlHaSDFL8EQ41GC2fs4tPjsg4.txt"

if os.path.exists(file_path):
    with open(file_path) as f:
        content = f.read()
        print(content)
else:
    print(f"File not found: {file_path}")

!wget -q -O - ipv4.icanhazip.com

! npm install -g localtunnel@2.0.2

!streamlit run app.py & npx localtunnel --port 8501

